-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1
-- Généré le : mar. 20 sep. 2022 à 17:16
-- Version du serveur : 10.4.24-MariaDB
-- Version de PHP : 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `squid`
--
CREATE DATABASE IF NOT EXISTS `squid` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `squid`;

--
-- Déchargement des données de la table `episode`
--

INSERT INTO `episode` (`id_episode`, `saison`, `nr`, `titre`, `resume`, `created_at`, `updated_at`) VALUES
(1, 1, 1, 'Un, deux, trois, soleil', 'Seong Gi-Hun est un homme malchanceux. Il a accumulé d\'énormes dettes auprès d\'usuriers tout en s\'éloignant de sa fille et de son ex-femme. Dans le métro, un homme lui propose de jouer à un jeu de ddakji pour de l\'argent, et lui offre l\'opportunité de jouer à d\'autres jeux avec des gains beaucoup plus élevés. Gi-Hun accepte, est endormi, et se réveille dans un dortoir avec 455 personnes identifiées seulement par un numéro sur leurs survêtements verts. Un groupe de gardes masqués habillés en rose arrive et explique que les joueurs sont tous dans une situation financières difficile, mais recevront plusieurs milliards de won en prix si ils peuvent remporter 6 jeux. Les jeux sont supervisés par le \"Front Man\", un homme masqué habillé en noir. Gi-Hun se lie d\'amitié avec le joueur 001, un vieil homme souffrant d\'une tumeur au cerveau. Il reconnait deux autres joueurs : Cho Sang-woo, un ami d\'enfance devenu courtier en investissements et la joueuse 067, une pickpocket qui a volé de l\'argent à Gi-Hun après avoir remporté un pari sur une course de chevaux. Le premier jeu est \"un, deux, trois, soleil\", où toute personne en mouvement est abattue sur place, révélant la nature sadique du jeu. La moitié des participants paniquent et tentent de fuir en réalisant cela, tournant le jeu en un massacre. Avec l\'aide de Sang-woo et du joueur 199, Gi-hun parvient à finir le premier jeu en vie. ', '2022-09-20 14:58:16', '2022-09-20 15:07:12'),
(2, 1, 2, 'Enfer', 'Avec plus de la moitié des joueurs tués dans le premier jeu, de nombreux survivants demandent à être libérés. Utilisant la troisième clause du jeu, ils votent de justesse pour annuler le jeu et renvoyer tout le monde chez soi, mais sans prix. De retour à Séoul, Gi-hun se rend à la police mais personne ne croit son histoire excepté le détectrive Hwang Jun-ho, dont le frère a reçu la même carte d\'invitation et disparu après. Les joueurs sont invités à entrer à nouveau dans le jeu, et beaucoup se décident à retourner par désespoir. Cela inclut Gi-hun, dont la mère nécessite une opération chirurgicale ; Sang-woo qui est sur le point d\'être arrêté pour fraude financière ; le joueur 001 qui ne souhaite pas mourir dans le monde extérieur ; la joueuse 067 qui désire secourir ses parents de Corée du Nord et sortir son petit frère d\'un orphelinat ; le joueur 199, un migrant Pakistanais qui a attaqué et blessé gravement son patron pour avoir retenu son salaire ; et le joueur 101, nommé Jang Deok-su, un gangster en fuite à cause de ses dettes de jeu et ex-patrons. Jun-ho suit secrètement Gi-hun lorsqu\'il est repris par les gardes.', '2022-09-20 15:05:41', '2022-09-20 15:07:24'),
(3, 1, 3, 'L\'homme au parapluie', 'Jun-Ho infiltre avec succès le jeu en se déguisant lui-même en un garde masqué, révélant que le jeu est localisé sur une île éloignée et abandonnée. Les joueurs sont maintenant plus préparés et commencent à former des alliances. Gi-hun, Sang-woo et les joueurs 001 et 199 font équipes. La joueuse 067 explore une bouche d\'aération et voit les ouvriers fondrent des pots de sucre. Le second jeu est révélé comme étant le Ppopgi, où chaque joueur doit extraire parfaitement une forme estampée d\'un Dalgona en 10 minutes. Sang-woo apprend la découverte de la joueuse 067 et reconnait le jeu à l\'avance, mais n\'avertit pas ses équipiers et choisi la forme la plus simple pour lui. Gi-hun se retrouve avec la forme la plus difficile, un parapluie, mais est capable de finir le jeu en léchant le dos du biscuit pour le faire fondre. La joueuse 212, une femme tapageuse, aide Deok-su à compléter le jeu avec un briquet qu\'elle avait caché. Un joueur sur le point d\'être éxécuté prend un garde en otage et le force à se démasquer. Choqué de voir que ce garde est est un jeune homme, le joueur se suicide et le garde est tué par le Front-Man pour avoir révélé son identité. ', '2022-09-20 15:06:18', '2022-09-20 15:07:36'),
(4, 1, 4, 'L\'équipe avant tout', 'Le joueur 111, un docteur en disgrâce, travaille secrêtement avec un petit groupe de gardes pour extraire des organes de joueurs décédés et les vendre sur le marché noir, en échange d\'informations sur les prochaines jeux. Dans le dortoire, lorsque Deok-Su tue un joueur qui l\'accusait de prendre de la nourriture en plus des autres, les gardes ne font rien pour le stopper et la prime de victoire augmente. Réalisant qu\'ils peuvent librement tuer d\'autres joueurs pour augmenter la prime, Deok-su et son gang déclenchent une émeute massive après que les lumières s\'éteignent, ce qui pousse les joueurs à s\'attaquer. Le groupe de Gi-hun parvient à survivre et s\'échangent leurs noms pour instaurer une confiance. Le joueur 199 est Ali Abdul et la joueuse 067 est Kang Sae-byeok. Le joueur 001, à cause de sa tumeur au cerveau, ne parvient pas à se souvenir son nom. La joueuse 212, nommée Han Mi-nyeo, rejoint l\'équipe de Deok-su. Pour le troisième jeu, les joueurs doivent former des groupes de 10. Pour l\'équipe de Gi-hun, Sae-byeok recrute la joueuse 240, une jeune fille proche de son âge. Le jeu se révèle être le Tir à la corde, sur deux plates-formes surélevées, où une équipe gagne en entrainant l\'équipe adverse hors de la plate-forme, provoquant une chute mortelle des joueurs de l\'équipe perdante. Deok-su, ayant appris la nature du jeu par le joueur 111, ne choisi que des hommes forts et rejecte Mi-nyeo, qui rejoint l\'équipe de Gi-hun. Après que l\'équipe de Deok-su ait remporté son match facilement, l\'équipe de Gi-hun doit affronter une autre équipe entièrement masculine. ', '2022-09-20 15:08:09', '2022-09-20 15:08:09'),
(5, 1, 5, 'Un monde juste', 'L\'équipe de Gi-hun parvient à remporter leur match de Tir à la corde grâce à la stratégie du joueur 001 et réflexion rapide de Sang-woo. Anticipant une autre émeute, ils construisent une barricade et passent la nuit à prendre des tours de garde. Mais l\'équipe de Deok-su n\'attaque finalement pas. Gi-hun se rappelle d\'une situation similaire il y a des années où lui et d\'autres travailleurs d\'une usine automobile protèstèrent contre un licenciement massif, ce qui a causé la trajectoire descendante de la vie de Gi-hun. La joueuse 240 tente de se lier d\'amitié avec Sae-byeok, mais qui ne rend pas la pareille. Jun-ho est témoin du prélévement d\'organes parce que le garde dont il a volé l\'identité en faisait partie. Le trafic est découvert après que l\'identité de Ji-hun soit découverte et suite à une altercation entre le joueur 111 et les gardes renégats. A l\'exception de Ji-hun, toutes les personnes impliquées dans ce trafic sont finalement abattues, y compris le joueur 111. Le Front Man lance alors une chasse à l\'homme pour retrouver Jun-ho, qui parvient à s\'infiltrer dans le bureau du Front Man et découvre que le jeu existe depuis 30 ans, et que son frère disparu l\'a remporté en 2015. ', '2022-09-20 15:08:53', '2022-09-20 15:09:15'),
(6, 1, 6, 'Gganbu', 'Les joueurs découvrent les corps pendus du joueur 111 et conspirateurs du trafic d\'organes, tués pour tricherie, et sont assurés que les jeux sont conçus pour donner à chaque joueur une chance équitable de gagner. Pour le quatrième jeu, les joueurs doivent former des paires, mais découvrent qu\'au lieu de jouer en équipe, ils vont devoir s\'affronter dans un Jeu de billes de leur choix. Celui qui récupère toutes les billes de son partenaire en 30 minutes gagne et survit. Sae-byeok et la joueuse 240, nommée Ji-yeong, échangent leurs histoires de vie. Ji-yeong constate que Sae-byeok a plus à vivre et se sacrifie en perdant volontairement la partie. Sang-woo trompe Ali en usant de sa gentillesse et confiance pour qu\'il lui laisse ses billes et gagne. Deok-su gagne contre son partenaire et homme de main, le joueur 278. Gi-hun exploite la démense du joueur 001 pour le battre, pour découvrir que le vieil homme était conscient de la tromperie tout ce temps. Le joueur 001, qui se souvient s\'appeller Oh Il-nam, lui donne cependant sa dernière bille pour lui permettre de gagner, car il est son gganbu (ami fidèle). Gi-hun et Sae-byeok sont traumatisés par la mort de leurs amis. ', '2022-09-20 15:09:48', '2022-09-20 15:10:09'),
(7, 1, 7, 'V.I.P', 'Les joueurs rentrent au dortoire et retrouvent Mi-nyeo, toujours en vie, qui n\'avait pas de partenaire pour le jeu de bille et a été exempté alors que tout le monde la croyait éxécutée. Des V.I.P étrangers ayant parié sur les jeux à distance, arrivent pour regarder et parier sur les prochaines épreuves. Jun-ho, se faisant passer pour l\'un des serviteurs, est sexuellement proposé à l\'un d\'eux. Dans une chambre privée, il attaque le VIP, enregistre ses aveux et s\'échappe de l\'île. Pendant ce temps, dans le cinquième jeu, les joueurs doivent traverser un long pont composé de paires de panneaux en verre. L\'un des panneau est en verre trempé et l\'autre en verre ordinaire, ce dernier ne pouvant supporter un poid humain et entrainant une chute mortelle du pont. Les joueurs en tête de file tombent au fur et à mesure qu\'ils testent les panneaux. Deok-su arrive finalement en tête et refuse de bouger malgré le temps imparti, défiant les autres de le dépasser. Mi-nyeo fait semblant d\'accepter mais l\'attrape et, pour se venger de sa trahison, l\'entraîne avec elle dans le vide. Le joueur 017, un ancien verrier, arrive en tête et révèle qu\'il peut différencier les verres, permettant aux derniers joueurs d\'avancer jusqu\'à ce que le Front-Man éteigne les lumières, retirant cet avantage. Avec le temps qui arrive à terme, Sang-woo pousse le joueur dans le vide pour révéler le dernier panneau en verre ordinaire. Seuls Gi-hun, Sang-woo et Sae-byeok survivent à l\'épreuve. Cette dernière se termine par l\'explosion des panneaux restants dont le verre blesse les trois survivants. ', '2022-09-20 15:10:41', '2022-09-20 15:10:41'),
(8, 1, 8, 'Leader', 'En temps que finalistes, Gi-hun, Sang-woo et Sae-byeok reçoivent des vêtements normaux et un dîner. Sae-byeok cache une blessure grave reçue par arme blanche lors de l\'explosion du pont de verre. Après avoir dîner, chaque joueur est laissé avec un couteau à viande. Gi-hun suggère à Sae-byeok qu\'ils devraient s\'allier contre Sang-woo, réalisant qu\'il fera tout pour gagner. Sae-byeok supplie plutôt Gi-hun de se promettre que celui qui gagner le jeu aidera les êtres chers de l\'autre. Gi-hun s\'apprête à tuer Sang-woo lorsque ce dernier tombe endormi, but Sae-byeok l\'arrête, lui disant qu\'il n\'est pas un meurtrier. La blessure de Sae-byeok s\'aggrave, incitant Gi-hun a appeler à l\'aide. Les gardes arrivent cependant pour récupérer son cadavre car Sang-woo profite de l\'absence de Gi-hun pour la tuer. Furieux et le coeur brisé, Gi-hun tente d\'attaque Sang-woo mais est maitrisé par les gardes. Pendant ce temps, Jun-ho arrive sur une autre île mais est rapidement rattrapé par le Front Man et ses gardes. Au grand choc de Jun-ho, le Front Man se révèle être In-ho, le frère disparu de Jun-ho. In-ho tente de recruter son frère, qui refuse. Il tire alors sur Jun-ho dans l\'épaule, le faisant tomber du bord d\'une falaise dans la mer. ', '2022-09-20 15:12:08', '2022-09-20 15:12:08'),
(9, 1, 9, 'Jour de chance', 'Dans le jeu final qui est le Squid game, jeu du calamar, où l\'attaquant doit atteindre un cercle en évitant le défenseur, Gi-hun parvient à battre Sang-woo après un combat brutal mais refuse de le tuer. Il supplie Sang-woo de stopper le jeu en utilisant à nouveau la troisième clause. Sang-woo se poignarde à la place dans le cou et demande à Gi-hun de s\'occuper de sa mère, avant de mourir. Gi-hun est ramené à Séoul avec une carte bancaire contenant le prix. Il découvre cependant que sa mère est décédée seule des suites de sa maladie. Un an plus tard, Gi-hun reste traumatisé n\'a pas touché à son prix par culpabilité. Il reçoit une carte d\'invitation de son gganbu, et trouve Oh Il-nam en vie sur son lit de mort à cause de la tumeur. Il-nam révèle qu\'il est en réalité le créateur du jeu, et qu\'il l\'a crée pour divertir les riches qui s\'ennuyaient comme lui. Il a choisi des jeux auquel il jouait enfant et se sachant mourrant, a voulu participer. Oh il-nam veut prouver à Gi-hun que les humains manquent d\'empathie en pariant qu\'un homme inconscient allongé dans un coin de rue ne sera pas aidé avant minuit. L\'homme est cependant secouru juste avant l\'heure de fin du paris et Oh il-nam meurt peu après. Gi-hun parvient à retrouver le frère de Sae-byeok et le confie à la mère de Sang-woo à qui il donne une partie du prix gagné. Alors qu\'il se rend à l\'aéroport pour rejoindre sa fille qui a déménagé avec son ex-femme à Los Angeles, il reconnaît le recruteur jouant au ddakji avec un autre homme désespéré. Il parvient à récuperer la carte d\'invitation du joueur et appelle le numéro pour demander qui dirige désormais le jeu. La personne au bout du fil lui ordonne de rentrer dans l\'avion mais Gi-hun raccroche et quitte l\'aéroport.', '2022-09-20 15:12:34', '2022-09-20 15:12:34');

--
-- Déchargement des données de la table `user`
--

INSERT INTO `user` (`id_user`, `login`, `password`) VALUES
(1, 'jef', 'jef'),
(2, 'bob', 'bob'),
(3, 'admin', 'admin'),
(4, 'bill', 'bill'),
(5, 'john', 'john'),
(6, 'mark', 'mark');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
